# Use git source instead of CDN to avoid FFI issues
source 'https://github.com/CocoaPods/Specs.git'

ENV['RCT_USE_PREBUILT_RNCORE'] = '1'
ENV['RCT_USE_RN_DEP'] = '1'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# Flutter module integration
# TEMPORARILY COMMENTED OUT - uncomment after implementing native bridges (Tasks 6.2/6.3)
# flutter_application_path = '../super_dash'
# load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'S3App' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Install Flutter module pods
  # TEMPORARILY COMMENTED OUT - uncomment after implementing native bridges (Tasks 6.2/6.3)
  # install_all_flutter_pods(flutter_application_path)

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    
    # Flutter post-install hook
    # TEMPORARILY COMMENTED OUT - uncomment after implementing native bridges (Tasks 6.2/6.3)
    # flutter_post_install(installer) if defined?(flutter_post_install)

    installer.pods_project.targets.each do |target|
      next unless %w[glog Flipper-Glog].include?(target.name)
      raise "Blocked pod '#{target.name}' detected during install. Remove glog-related dependencies."
    end
  end
end
