#!/usr/bin/env bash
# Verify E2E flows work with current UI and testIDs
# This script checks testID alignment and runs basic validation

set -e

echo "🔍 E2E Flow Verification Script"
echo "================================"
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if Maestro is installed
echo "📦 Checking Maestro installation..."
if ! command -v maestro &> /dev/null; then
    echo -e "${RED}❌ Maestro not found${NC}"
    echo "Install with: curl -Ls \"https://get.maestro.mobile.dev\" | bash"
    exit 1
fi
echo -e "${GREEN}✅ Maestro installed${NC}"
echo ""

# Check if flows exist
echo "📄 Checking flow files..."
FLOWS=("onboarding" "input_chart" "full_journey" "moderation")
for flow in "${FLOWS[@]}"; do
    if [ -f "e2e/flows/${flow}.yaml" ]; then
        echo -e "${GREEN}✅ ${flow}.yaml found${NC}"
    else
        echo -e "${RED}❌ ${flow}.yaml missing${NC}"
        exit 1
    fi
done
echo ""

# Validate YAML syntax (basic check)
echo "🔧 Validating YAML files..."
for flow in "${FLOWS[@]}"; do
    # Basic YAML validation - check if file is readable and has appId
    if grep -q "appId: com.s3app" "e2e/flows/${flow}.yaml"; then
        echo -e "${GREEN}✅ ${flow}.yaml valid${NC}"
    else
        echo -e "${RED}❌ ${flow}.yaml missing appId${NC}"
        exit 1
    fi
done
echo ""

# Check testID alignment
echo "🎯 Checking testID alignment..."
echo ""

# Define expected testIDs from flows (testid:file format)
EXPECTED_TESTIDS=(
    "get-started-button:OnboardingScreen.tsx"
    "tab-birth-data:InputScreen.tsx"
    "tab-upload-pdf:InputScreen.tsx"
    "field-date:InputScreen.tsx"
    "field-time:InputScreen.tsx"
    "field-location:InputScreen.tsx"
    "button-compute-chart:InputScreen.tsx"
    "result-screen:ResultScreen.tsx"
    "primary-system-name:ResultScreen.tsx"
    "view-why-button:ResultScreen.tsx"
    "disclaimer-text:ResultScreen.tsx"
    "why-screen-app-bar:WhyScreen.tsx"
)

# Check each testID in source code
for entry in "${EXPECTED_TESTIDS[@]}"; do
    testid="${entry%%:*}"
    file="${entry##*:}"
    
    # Search for testID in source
    if grep -r "testID=\"${testid}\"" src/ &> /dev/null; then
        echo -e "${GREEN}✅ ${testid}${NC}"
    else
        echo -e "${RED}❌ ${testid}${NC} NOT FOUND"
        echo "   Expected in: ${file}"
    fi
done

# Check generated testIDs
echo -e "${YELLOW}⏭️  why-screen-app-bar-back (generated by AppBar)${NC}"
echo ""

# Summary
echo "📊 Verification Summary"
echo "======================="
echo -e "${GREEN}✅ Maestro installed${NC}"
echo -e "${GREEN}✅ All flow files present${NC}"
echo -e "${GREEN}✅ YAML syntax valid${NC}"
echo ""

echo "🚀 Ready to run E2E tests!"
echo ""
echo "Run tests with:"
echo "  make e2e-ios FLOW=onboarding"
echo "  make e2e-ios FLOW=input_chart"
echo "  make e2e-ios FLOW=full_journey"
echo "  make e2e-ios FLOW=moderation"
echo ""
echo "Or run all flows:"
echo "  make e2e"
echo ""
